/*****************************************************************************
 *                                                                           *
 *   FAZGST.C    (GSTATE.C)                                                  *
 *                                                                           *
 *   Worldgroup 3.2 conversion                     - R. Hadsall 4/24/2021    *
 *   The Major BBS v10 conversion                  - R. Hadsall 4/18/2023    *
 *   Minor edits to allow WG32/V10 from same kit   - R. Hadsall 8/5/2024     *
 *                                                                           *
 * Copyright (C) 2005-2024 Rick Hadsall.  All Rights Reserved.               *
 *                                                                           *
 * This program is free software: you can redistribute it and/or modify      *
 * it under the terms of the GNU Affero General Public License as published  *
 * by the Free Software Foundation, either version 3 of the License, or      *
 * (at your option) any later version.                                       *
 *                                                                           *
 * This program is distributed in the hope that it will be useful,           *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of            *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the              *
 * GNU Affero General Public License for more details.                       *
 *                                                                           *
 * You should have received a copy of the GNU Affero General Public License  *
 * along with this program. If not, see <https://www.gnu.org/licenses/>.     *
 *                                                                           *
 * Additional Terms for Contributors:                                        *
 * 1. By contributing to this project, you agree to assign all right, title, *
 *    and interest, including all copyrights, in and to your contributions   *
 *    to Rick Hadsall and Elwynor Technologies.                              *
 * 2. You grant Rick Hadsall and Elwynor Technologies a non-exclusive,       *
 *    royalty-free, worldwide license to use, reproduce, prepare derivative  *
 *    works of, publicly display, publicly perform, sublicense, and          *
 *    distribute your contributions                                          *
 * 3. You represent that you have the legal right to make your contributions *
 *    and that the contributions do not infringe any third-party rights.     *
 * 4. Rick Hadsall and Elwynor Technologies are not obligated to incorporate *
 *    any contributions into the project.                                    *
 * 5. This project is licensed under the AGPL v3, and any derivative works   *
 *    must also be licensed under the AGPL v3.                               *
 * 6. If you create an entirely new project (a fork) based on this work, it  *
 *    must also be licensed under the AGPL v3, you assign all right, title,  *
 *    and interest, including all copyrights, in and to your contributions   *
 *    to Rick Hadsall and Elwynor Technologies, and you must include these   *
 *    additional terms in your project's LICENSE file(s).                    *
 *                                                                           *
 * By contributing to this project, you agree to these terms.                *
 *                                                                           *
 *****************************************************************************/

#include "gcomm.h"
#include "fazdat.h"
#include "elwfaz.h"

extern struct object objcts[TOTOBJ];

struct state states[TOTSTT]={
/* 000 */ {"in the jungle by the southern city entrance","on the ground",
          FAZ100,
          nocmd,
          NULL,
          2,{&objcts[0],&objcts[80],NULL,NULL,NULL,NULL},
          &states[285],&states[37],&states[9],&states[8]},
/* 001 */ {"at the spaceport","on the tarmac",
          FAZ101,
          nocmd,
          NULL,
          1,{&objcts[80],NULL,NULL,NULL,NULL,NULL},
          NULL,NULL,NULL,&states[286]},
/* 002 */ {"in the jungle by the northern city entrance","on the ground",
          FAZ102,
          nocmd,
          NULL,
          2,{&objcts[1],&objcts[80],NULL,NULL,NULL,NULL},
          &states[55],&states[287],&states[21],&states[22]},
/* 003 */ {"in the jungle by the western city entrance","on the ground",
          FAZ103,
          nocmd,
          NULL,
          2,{&objcts[2],&objcts[80],NULL,NULL,NULL,NULL},
          &states[29],&states[4],&states[288],&states[30]},
/* 004 */ {"in the jungle, with a wall to the east","in the underbrush",
          FAZ107,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[3],&states[5],NULL,&states[31]},
/* 005 */ {"in the jungle, with a wall to the east","in the underbrush",
          FAZ107,
          nocmd,
          NULL,
          1,{&objcts[3],NULL,NULL,NULL,NULL,NULL},
          &states[4],&states[6],NULL,&states[32]},
/* 006 */ {"in the jungle, by the southwest corner of a wall","in the underbrush",
          FAZ108,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[5],&states[34],&states[7],&states[33]},
/* 007 */ {"in the jungle, with a wall to the north","in the underbrush",
          FAZ130,
          nocmd,
          NULL,
          3,{&objcts[4],&objcts[120],&objcts[119],NULL,NULL,NULL},
          NULL,&states[35],&states[8],&states[6]},
/* 008 */ {"in the jungle, with a wall to the north","in the underbrush",
          FAZ104,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          NULL,&states[36],&states[0],&states[7]},
/* 009 */ {"in the jungle, with a wall to the north","in the underbrush",
          FAZ104,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          NULL,&states[38],&states[10],&states[0]},
/* 010 */ {"in the jungle, with a wall to the north","in the underbrush",
          FAZ104,
          nocmd,
          NULL,
          1,{&objcts[0],NULL,NULL,NULL,NULL,NULL},
          NULL,&states[39],&states[11],&states[9]},
/* 011 */ {"in the jungle, with a wall to the north","in the underbrush",
          FAZ104,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          NULL,&states[40],&states[12],&states[10]},
/* 012 */ {"in the jungle, by the southeast corner of a wall","in the underbrush",
          FAZ109,
          nocmd,
          NULL,
          1,{&objcts[1],NULL,NULL,NULL,NULL,NULL},
          &states[13],&states[41],&states[43],&states[11]},
/* 013 */ {"in the jungle, with a wall to the west","in the underbrush",
          FAZ105,
          nocmd,
          NULL,
          1,{&objcts[2],NULL,NULL,NULL,NULL,NULL},
          &states[1],&states[12],&states[44],NULL},
/* 014 */ {"in the jungle, with a wall to the west","in the underbrush",
          FAZ105,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[15],&states[1],&states[46],NULL},
/* 015 */ {"in the jungle, with a wall to the west","in the underbrush",
          FAZ105,
          nocmd,
          NULL,
          1,{&objcts[3],NULL,NULL,NULL,NULL,NULL},
          &states[16],&states[14],&states[47],NULL},
/* 016 */ {"in the jungle, with a wall to the west","in the underbrush",
          FAZ105,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[17],&states[15],&states[48],NULL},
/* 017 */ {"in the jungle, strangely enough","in the underbrush",
          FAZ105,
          nocmd,
          NULL,
          1,{&objcts[4],NULL,NULL,NULL,NULL,NULL},
          &states[18],&states[16],&states[49],NULL},
/* 018 */ {"in the jungle, with a wall to the west","in the underbrush",
          FAZ105,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[19],&states[17],&states[50],NULL},
/* 019 */ {"in the jungle, by the northeast corner of a wall","in the underbrush",
          FAZ110,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[52],&states[18],&states[51],&states[20]},
/* 020 */ {"in the jungle, with a wall to the south","in the underbrush",
          FAZ106,
          nocmd,
          NULL,
          1,{&objcts[0],NULL,NULL,NULL,NULL,NULL},
          &states[53],NULL,&states[19],&states[21]},
/* 021 */ {"in the jungle, with a wall to the south","in the underbrush",
          FAZ106,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[54],NULL,&states[20],&states[2]},
/* 022 */ {"in the jungle, with a wall to the south","in the underbrush",
          FAZ106,
          nocmd,
          NULL,
          1,{&objcts[1],NULL,NULL,NULL,NULL,NULL},
          &states[56],NULL,&states[2],&states[23]},
/* 023 */ {"in the jungle, with a wall to the south","in the underbrush",
          FAZ106,
          nocmd,
          NULL,
          1,{&objcts[2],NULL,NULL,NULL,NULL,NULL},
          &states[57],NULL,&states[22],&states[24]},
/* 024 */ {"in the jungle, with a wall to the south","in the underbrush",
          FAZ131,
          nocmd,
          NULL,
          1,{&objcts[121],NULL,NULL,NULL,NULL,NULL},
          &states[58],NULL,&states[23],&states[25]},
/* 025 */ {"in the jungle, strangely enough","in the underbrush",
          FAZ111,
          nocmd,
          NULL,
          1,{&objcts[3],NULL,NULL,NULL,NULL,NULL},
          &states[59],&states[26],&states[24],&states[61]},
/* 026 */ {"in the jungle, with a wall to the east","in the underbrush",
          FAZ107,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[25],&states[27],NULL,&states[62]},
/* 027 */ {"in the jungle, with a wall to the east","in the underbrush",
          FAZ107,
          nocmd,
          NULL,
          1,{&objcts[4],NULL,NULL,NULL,NULL,NULL},
          &states[26],&states[28],NULL,&states[63]},
/* 028 */ {"in the jungle, with a wall to the east","in the underbrush",
          FAZ107,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[27],&states[29],NULL,&states[64]},
/* 029 */ {"in the jungle, with a wall to the east","in the underbrush",
          FAZ107,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[28],&states[3],NULL,&states[65]},
/* 030 */ {"in the jungle","in the underbrush",
          FAZ113,
          nocmd,
          NULL,
          1,{&objcts[0],NULL,NULL,NULL,NULL,NULL},
          &states[65],&states[31],&states[3],&states[66]},
/* 031 */ {"in the jungle","in the underbrush",
          FAZ113,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[30],&states[32],&states[4],&states[67]},
/* 032 */ {"in the jungle","in the underbrush",
          FAZ113,
          nocmd,
          NULL,
          1,{&objcts[1],NULL,NULL,NULL,NULL,NULL},
          &states[31],&states[33],&states[5],&states[68]},
/* 033 */ {"in the jungle","in the underbrush",
          FAZ114,
          nocmd,
          NULL,
          1,{&objcts[2],NULL,NULL,NULL,NULL,NULL},
          &states[32],&states[33],&states[6],&states[69]},
/* 034 */ {"in the jungle","in the underbrush",
          FAZ114,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[6],&states[34],&states[35],&states[34]},
/* 035 */ {"in the jungle","in the underbrush",
          FAZ115,
          nocmd,
          NULL,
          1,{&objcts[3],NULL,NULL,NULL,NULL,NULL},
          &states[7],&states[70],&states[36],&states[34]},
/* 036 */ {"in the jungle","in the underbrush",
          FAZ115,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[8],&states[71],&states[37],&states[35]},
/* 037 */ {"in the jungle","in the underbrush",
          FAZ115,
          nocmd,
          NULL,
          1,{&objcts[4],NULL,NULL,NULL,NULL,NULL},
          &states[0],&states[72],&states[38],&states[36]},
/* 038 */ {"in the jungle","in the underbrush",
          FAZ115,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[9],&states[73],&states[39],&states[37]},
/* 039 */ {"in the jungle","in the underbrush",
          FAZ115,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[10],&states[74],&states[40],&states[38]},
/* 040 */ {"in the jungle","in the underbrush",
          FAZ115,
          nocmd,
          NULL,
          1,{&objcts[0],NULL,NULL,NULL,NULL,NULL},
          &states[11],&states[75],&states[41],&states[39]},
/* 041 */ {"in the jungle","in the underbrush",
          FAZ116,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[12],&states[76],&states[42],&states[40]},
/* 042 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[1],NULL,NULL,NULL,NULL,NULL},
          &states[43],&states[77],&states[41],&states[41]},
/* 043 */ {"in the jungle","in the underbrush",
          FAZ116,
          nocmd,
          NULL,
          1,{&objcts[2],NULL,NULL,NULL,NULL,NULL},
          &states[44],&states[42],&states[43],&states[12]},
/* 044 */ {"in the jungle","in the underbrush",
          FAZ117,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[45],&states[43],&states[78],&states[13]},
/* 045 */ {"in the jungle","in the underbrush",
          FAZ117,
          nocmd,
          NULL,
          1,{&objcts[3],NULL,NULL,NULL,NULL,NULL},
          &states[46],&states[44],&states[79],&states[1]},
/* 046 */ {"in the jungle","in the underbrush",
          FAZ117,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[47],&states[45],&states[80],&states[14]},
/* 047 */ {"in the jungle","in the underbrush",
          FAZ117,
          nocmd,
          NULL,
          1,{&objcts[4],NULL,NULL,NULL,NULL,NULL},
          &states[48],&states[46],&states[80],&states[15]},
/* 048 */ {"in the jungle","in the underbrush",
          FAZ137,
          nocmd,
          NULL,
          1,{&objcts[127],NULL,NULL,NULL,NULL,NULL},
          &states[49],&states[47],&states[80],&states[16]},
/* 049 */ {"in the jungle","in the underbrush",
          FAZ117,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[50],&states[48],&states[49],&states[17]},
/* 050 */ {"in the jungle","in the underbrush",
          FAZ117,
          nocmd,
          NULL,
          1,{&objcts[0],NULL,NULL,NULL,NULL,NULL},
          &states[51],&states[49],&states[50],&states[18]},
/* 051 */ {"in the jungle","in the underbrush",
          FAZ118,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[52],&states[50],&states[51],&states[19]},
/* 052 */ {"in the jungle","in the underbrush",
          FAZ118,
          nocmd,
          NULL,
          1,{&objcts[1],NULL,NULL,NULL,NULL,NULL},
          &states[51],&states[19],&states[52],&states[53]},
/* 053 */ {"in the jungle","in the underbrush",
          FAZ119,
          nocmd,
          NULL,
          1,{&objcts[2],NULL,NULL,NULL,NULL,NULL},
          &states[81],&states[20],&states[52],&states[54]},
/* 054 */ {"in the jungle","in the underbrush",
          FAZ119,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[81],&states[21],&states[53],&states[55]},
/* 055 */ {"in the jungle","in the underbrush",
          FAZ119,
          nocmd,
          NULL,
          1,{&objcts[3],NULL,NULL,NULL,NULL,NULL},
          &states[82],&states[2],&states[54],&states[56]},
/* 056 */ {"in the jungle","in the underbrush",
          FAZ119,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[83],&states[22],&states[55],&states[57]},
/* 057 */ {"in the jungle","in the underbrush",
          FAZ119,
          nocmd,
          NULL,
          1,{&objcts[4],NULL,NULL,NULL,NULL,NULL},
          &states[84],&states[23],&states[56],&states[58]},
/* 058 */ {"in the jungle","in the underbrush",
          FAZ119,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[85],&states[24],&states[57],&states[59]},
/* 059 */ {"in the jungle","in the underbrush",
          FAZ112,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[86],&states[25],&states[58],&states[60]},
/* 060 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[0],NULL,NULL,NULL,NULL,NULL},
          &states[60],&states[61],&states[59],&states[87]},
/* 061 */ {"in the jungle","in the underbrush",
          FAZ112,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[60],&states[62],&states[25],&states[87]},
/* 062 */ {"in the jungle","in the underbrush",
          FAZ113,
          nocmd,
          NULL,
          1,{&objcts[1],NULL,NULL,NULL,NULL,NULL},
          &states[61],&states[63],&states[26],&states[88]},
/* 063 */ {"in the jungle","in the underbrush",
          FAZ113,
          nocmd,
          NULL,
          1,{&objcts[2],NULL,NULL,NULL,NULL,NULL},
          &states[62],&states[64],&states[27],&states[89]},
/* 064 */ {"in the jungle","in the underbrush",
          FAZ134,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[63],&states[65],&states[28],&states[90]},
/* 065 */ {"in the jungle","in the underbrush",
          FAZ113,
          nocmd,
          NULL,
          1,{&objcts[3],NULL,NULL,NULL,NULL,NULL},
          &states[64],&states[30],&states[29],&states[91]},
/* 066 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[91],&states[67],&states[30],&states[66]},
/* 067 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[4],NULL,NULL,NULL,NULL,NULL},
          &states[66],&states[68],&states[31],&states[67]},
/* 068 */ {"in the jungle","in the underbrush",
          FAZ135,
          nocmd,
          NULL,
          1,{&objcts[126],NULL,NULL,NULL,NULL,NULL},
          &states[67],&states[69],&states[32],&states[88]},
/* 069 */ {"in the jungle","in the underbrush",
          FAZ121,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[68],&states[92],&states[33],&states[69]},
/* 070 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[0],NULL,NULL,NULL,NULL,NULL},
          &states[35],&states[70],&states[71],&states[34]},
/* 071 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[36],&states[71],&states[72],&states[70]},
/* 072 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[1],NULL,NULL,NULL,NULL,NULL},
          &states[37],&states[138],&states[73],&states[71]},
/* 073 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[2],NULL,NULL,NULL,NULL,NULL},
          &states[38],&states[138],&states[74],&states[72]},
/* 074 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[39],&states[74],&states[75],&states[73]},
/* 075 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[3],NULL,NULL,NULL,NULL,NULL},
          &states[40],&states[75],&states[76],&states[74]},
/* 076 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[41],&states[76],&states[77],&states[75]},
/* 077 */ {"standing near the platform","on the platform",
          FAZ139,
          cm77,
          NULL,
          2,{&objcts[4],&objcts[152],NULL,NULL,NULL,NULL},
          &states[42],&states[75],&states[149],&states[76]},
/* 078 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[79],&states[43],&states[149],&states[44]},
/* 079 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[80],&states[78],&states[150],&states[45]},
/* 080 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[0],NULL,NULL,NULL,NULL,NULL},
          &states[47],&states[79],&states[151],&states[46]},
/* 081 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[81],&states[54],&states[81],&states[82]},
/* 082 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[1],NULL,NULL,NULL,NULL,NULL},
          &states[254],&states[55],&states[81],&states[83]},
/* 083 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[2],NULL,NULL,NULL,NULL,NULL},
          &states[254],&states[56],&states[82],&states[84]},
/* 084 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[256],&states[57],&states[83],&states[85]},
/* 085 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[3],NULL,NULL,NULL,NULL,NULL},
          &states[256],&states[58],&states[84],&states[86]},
/* 086 */ {"in the jungle","in the underbrush",
          FAZ133,
          nocmd,
          NULL,
          1,{&objcts[125],NULL,NULL,NULL,NULL,NULL},
          &states[261],&states[59],&states[85],&states[87]},
/* 087 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[4],NULL,NULL,NULL,NULL,NULL},
          &states[87],&states[88],&states[62],&states[87]},
/* 088 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[87],&states[89],&states[62],&states[89]},
/* 089 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[88],&states[90],&states[63],&states[90]},
/* 090 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[0],NULL,NULL,NULL,NULL,NULL},
          &states[89],&states[91],&states[64],&states[91]},
/* 091 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[90],&states[66],&states[65],&states[66]},
/* 092 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[1],NULL,NULL,NULL,NULL,NULL},
          &states[69],&states[93],&states[33],&states[93]},
/* 093 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[2],NULL,NULL,NULL,NULL,NULL},
          &states[92],&states[94],&states[92],&states[94]},
/* 094 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[93],&states[95],&states[93],&states[95]},
/* 095 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[3],NULL,NULL,NULL,NULL,NULL},
          &states[94],&states[96],&states[94],&states[96]},
/* 096 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[95],&states[97],&states[95],&states[97]},
/* 097 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[4],NULL,NULL,NULL,NULL,NULL},
          &states[96],&states[98],&states[96],&states[98]},
/* 098 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[97],&states[99],&states[97],&states[99]},
/* 099 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[98],&states[100],&states[98],&states[104]},
/* 100 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[0],NULL,NULL,NULL,NULL,NULL},
          &states[99],&states[101],&states[99],&states[105]},
/* 101 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[100],&states[102],&states[100],&states[106]},
/* 102 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[1],NULL,NULL,NULL,NULL,NULL},
          &states[101],&states[103],&states[101],&states[107]},
/* 103 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[2],NULL,NULL,NULL,NULL,NULL},
          &states[102],&states[101],&states[102],&states[108]},
/* 104 */ {"in the jungle beside a statue","in front of the statue",
          FAZ150,
          cm104,
          NULL,
          1,{&objcts[141],NULL,NULL,NULL,NULL,NULL},
          &states[98],&states[105],&states[100],&states[105]},
/* 105 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[3],NULL,NULL,NULL,NULL,NULL},
          &states[104],&states[106],&states[100],&states[109]},
/* 106 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[105],&states[107],&states[101],&states[110]},
/* 107 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[4],NULL,NULL,NULL,NULL,NULL},
          &states[106],&states[108],&states[102],&states[111]},
/* 108 */ {"in the jungle, with the freenish","beside the freenish",
          FAZ136,
          cm108,
          NULL,
          2,{&objcts[131],&objcts[153],NULL,NULL,NULL,NULL},
          &states[107],&states[112],&states[103],&states[112]},
/* 109 */ {"in the jungle beside a statue","in front of the statue",
          FAZ149,
          cm109,
          NULL,
          1,{&objcts[141],NULL,NULL,NULL,NULL,NULL},
          &states[105],&states[110],&states[105],&states[110]},
/* 110 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[0],NULL,NULL,NULL,NULL,NULL},
          &states[109],&states[111],&states[106],&states[113]},
/* 111 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[110],&states[112],&states[107],&states[114]},
/* 112 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[1],NULL,NULL,NULL,NULL,NULL},
          &states[111],&states[115],&states[108],&states[115]},
/* 113 */ {"in the jungle beside a statue","in front of the statue",
          FAZ148,
          cm113,
          NULL,
          2,{&objcts[2],&objcts[141],NULL,NULL,NULL,NULL},
          &states[110],&states[114],&states[110],&states[114]},
/* 114 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[113],&states[115],&states[111],&states[116]},
/* 115 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[3],NULL,NULL,NULL,NULL,NULL},
          &states[114],&states[117],&states[112],&states[117]},
/* 116 */ {"in the jungle beside a statue","in front of the statue",
          FAZ147,
          cm116,
          NULL,
          1,{&objcts[141],NULL,NULL,NULL,NULL,NULL},
          &states[114],&states[117],&states[114],&states[118]},
/* 117 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[4],NULL,NULL,NULL,NULL,NULL},
          &states[116],&states[115],&states[115],&states[118]},
/* 118 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[117],&states[117],&states[117],&states[119]},
/* 119 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[118],&states[118],&states[118],&states[120]},
/* 120 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[0],NULL,NULL,NULL,NULL,NULL},
          &states[121],&states[119],&states[119],&states[112]},
/* 121 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[122],&states[120],&states[120],&states[120]},
/* 122 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[1],NULL,NULL,NULL,NULL,NULL},
          &states[123],&states[121],&states[121],&states[121]},
/* 123 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[2],NULL,NULL,NULL,NULL,NULL},
          &states[124],&states[122],&states[122],&states[118]},
/* 124 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[125],&states[123],&states[123],&states[123]},
/* 125 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[3],NULL,NULL,NULL,NULL,NULL},
          &states[126],&states[124],&states[124],&states[124]},
/* 126 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[127],&states[125],&states[125],&states[120]},
/* 127 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[4],NULL,NULL,NULL,NULL,NULL},
          &states[123],&states[126],&states[126],&states[128]},
/* 128 */ {"in the jungle","in the underbrush",
          FAZ161,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[127],&states[127],&states[127],&states[129]},
/* 129 */ {"in the thunderstorm","half-buried in the underbrush",
          FAZ160,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[136],&states[130],&states[128],&states[133]},
/* 130 */ {"in the thunderstorm","half-buried in the underbrush",
          FAZ160,
          nocmd,
          NULL,
          1,{&objcts[0],NULL,NULL,NULL,NULL,NULL},
          &states[129],&states[135],&states[128],&states[131]},
/* 131 */ {"in the thunderstorm","half-buried in the underbrush",
          FAZ160,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[135],&states[134],&states[130],&states[132]},
/* 132 */ {"in the thunderstorm","half-buried in the underbrush",
          FAZ160,
          nocmd,
          NULL,
          1,{&objcts[1],NULL,NULL,NULL,NULL,NULL},
          &states[133],&states[136],&states[131],&states[129]},
/* 133 */ {"in the thunderstorm","half-buried in the underbrush",
          FAZ160,
          nocmd,
          NULL,
          1,{&objcts[2],NULL,NULL,NULL,NULL,NULL},
          &states[134],&states[132],&states[137],&states[136]},
/* 134 */ {"in the thunderstorm","half-buried in the underbrush",
          FAZ160,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[131],&states[133],&states[135],&states[130]},
/* 135 */ {"in the thunderstorm","half-buried in the underbrush",
          FAZ160,
          nocmd,
          NULL,
          1,{&objcts[3],NULL,NULL,NULL,NULL,NULL},
          &states[130],&states[131],&states[136],&states[134]},
/* 136 */ {"in the thunderstorm","half-buried in the underbrush",
          FAZ160,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[132],&states[129],&states[128],&states[135]},
/* 137 */ {"standing before the nofzinger","on the ground",
          FAZ146,
          cm137,
          NULL,
          2,{&objcts[4],&objcts[140],NULL,NULL,NULL,NULL},
          &states[135],&states[131],&states[129],&states[133]},
/* 138 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[72],&states[139],&states[139],&states[139]},
/* 139 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[138],&states[140],&states[140],&states[140]},
/* 140 */ {"in the jungle","in the underbrush",
          FAZ123,
          nocmd,
          NULL,
          1,{&objcts[0],NULL,NULL,NULL,NULL,NULL},
          &states[139],&states[148],&states[141],&states[147]},
/* 141 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[143],&states[142],&states[147],&states[140]},
/* 142 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[1],NULL,NULL,NULL,NULL,NULL},
          &states[141],&states[143],&states[146],&states[148]},
/* 143 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[2],NULL,NULL,NULL,NULL,NULL},
          &states[142],&states[141],&states[145],&states[144]},
/* 144 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[148],&states[144],&states[143],&states[145]},
/* 145 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[3],NULL,NULL,NULL,NULL,NULL},
          &states[146],&states[147],&states[144],&states[143]},
/* 146 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[147],&states[145],&states[148],&states[142]},
/* 147 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[4],NULL,NULL,NULL,NULL,NULL},
          &states[145],&states[146],&states[140],&states[141]},
/* 148 */ {"in the jungle","in the underbrush",
          FAZ151,
          nocmd,
          NULL,
          1,{&objcts[142],NULL,NULL,NULL,NULL,NULL},
          &states[140],&states[144],&states[142],&states[146]},
/* 149 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[150],&states[80],&states[154],&states[78]},
/* 150 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[0],NULL,NULL,NULL,NULL,NULL},
          &states[151],&states[149],&states[153],&states[79]},
/* 151 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[154],&states[150],&states[152],&states[80]},
/* 152 */ {"in the jungle, next to the mongooosk","in front of the mongooosk",
          FAZ138,
          cm152,
          NULL,
          3,{&objcts[133],&objcts[134],&objcts[1],NULL,NULL,NULL},
          &states[155],&states[153],&states[157],&states[151]},
/* 153 */ {"in the jungle","in the underbrush",
          FAZ124,
          nocmd,
          NULL,
          1,{&objcts[2],NULL,NULL,NULL,NULL,NULL},
          &states[152],&states[154],&states[156],&states[150]},
/* 154 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[153],&states[151],&states[155],&states[149]},
/* 155 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[3],NULL,NULL,NULL,NULL,NULL},
          &states[156],&states[152],&states[160],&states[154]},
/* 156 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[157],&states[155],&states[159],&states[153]},
/* 157 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[4],NULL,NULL,NULL,NULL,NULL},
          &states[160],&states[156],&states[158],&states[152]},
/* 158 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[161],&states[159],&states[163],&states[157]},
/* 159 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[158],&states[160],&states[162],&states[156]},
/* 160 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[0],NULL,NULL,NULL,NULL,NULL},
          &states[159],&states[157],&states[161],&states[155]},
/* 161 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[162],&states[158],&states[166],&states[160]},
/* 162 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[1],NULL,NULL,NULL,NULL,NULL},
          &states[163],&states[161],&states[165],&states[159]},
/* 163 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[2],NULL,NULL,NULL,NULL,NULL},
          &states[166],&states[162],&states[164],&states[158]},
/* 164 */ {"in the jungle","in the underbrush",
          FAZ125,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[167],&states[165],&states[169],&states[163]},
/* 165 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[3],NULL,NULL,NULL,NULL,NULL},
          &states[164],&states[166],&states[168],&states[162]},
/* 166 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[165],&states[163],&states[167],&states[161]},
/* 167 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[4],NULL,NULL,NULL,NULL,NULL},
          &states[168],&states[164],&states[172],&states[166]},
/* 168 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[169],&states[167],&states[171],&states[165]},
/* 169 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[172],&states[168],&states[170],&states[164]},
/* 170 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[0],NULL,NULL,NULL,NULL,NULL},
          &states[249],&states[171],&states[175],&states[169]},
/* 171 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[170],&states[172],&states[174],&states[168]},
/* 172 */ {"in the jungle","beside the rock",
          FAZ140,
          nocmd,
          NULL,
          2,{&objcts[1],&objcts[135],NULL,NULL,NULL,NULL},
          &states[171],&states[169],&states[173],&states[167]},
/* 173 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[2],NULL,NULL,NULL,NULL,NULL},
          &states[174],&states[170],&states[178],&states[172]},
/* 174 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[175],&states[173],&states[177],&states[171]},
/* 175 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[3],NULL,NULL,NULL,NULL,NULL},
          &states[178],&states[174],&states[176],&states[170]},
/* 176 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[194],&states[177],&states[201],&states[175]},
/* 177 */ {"in the jungle","in the underbrush",
          FAZ126,
          nocmd,
          NULL,
          1,{&objcts[4],NULL,NULL,NULL,NULL,NULL},
          &states[176],&states[178],&states[202],&states[174]},
/* 178 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[177],&states[179],&states[194],&states[173]},
/* 179 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[178],&states[180],&states[194],&states[173]},
/* 180 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[0],NULL,NULL,NULL,NULL,NULL},
          &states[179],&states[181],&states[179],&states[179]},
/* 181 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[180],&states[182],&states[180],&states[180]},
/* 182 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[1],NULL,NULL,NULL,NULL,NULL},
          &states[181],&states[182],&states[183],&states[183]},
/* 183 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[2],NULL,NULL,NULL,NULL,NULL},
          &states[182],&states[184],&states[182],&states[182]},
/* 184 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[183],&states[185],&states[183],&states[183]},
/* 185 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[3],NULL,NULL,NULL,NULL,NULL},
          &states[184],&states[193],&states[186],&states[192]},
/* 186 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[184],&states[187],&states[192],&states[185]},
/* 187 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[4],NULL,NULL,NULL,NULL,NULL},
          &states[186],&states[188],&states[191],&states[193]},
/* 188 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[187],&states[186],&states[190],&states[189]},
/* 189 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[193],&states[189],&states[188],&states[190]},
/* 190 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[0],NULL,NULL,NULL,NULL,NULL},
          &states[191],&states[192],&states[189],&states[188]},
/* 191 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[192],&states[190],&states[193],&states[187]},
/* 192 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[1],NULL,NULL,NULL,NULL,NULL},
          &states[184],&states[191],&states[185],&states[186]},
/* 193 */ {"standing before the Orb That Talks","in the underbrush",
          FAZ152,
          cm193,
          NULL,
          3,{&objcts[2],&objcts[143],&objcts[144],NULL,NULL,NULL},
          &states[185],&states[189],&states[187],&states[191]},
/* 194 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[202],&states[176],&states[195],&states[178]},
/* 195 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[3],NULL,NULL,NULL,NULL,NULL},
          &states[196],&states[201],&states[195],&states[194]},
/* 196 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[200],&states[195],&states[197],&states[202]},
/* 197 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[4],NULL,NULL,NULL,NULL,NULL},
          &states[198],&states[200],&states[197],&states[196]},
/* 198 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[199],&states[197],&states[199],&states[200]},
/* 199 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[199],&states[199],&states[203],&states[198]},
/* 200 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[0],NULL,NULL,NULL,NULL,NULL},
          &states[197],&states[196],&states[198],&states[201]},
/* 201 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[195],&states[202],&states[200],&states[176]},
/* 202 */ {"standing by a wrecked spaceship","beside the spaceship",
          FAZ141,
          nocmd,
          NULL,
          3,{&objcts[1],&objcts[136],&objcts[137],NULL,NULL,NULL},
          &states[201],&states[194],&states[196],&states[177]},
/* 203 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[2],NULL,NULL,NULL,NULL,NULL},
          &states[204],&states[197],&states[198],&states[199]},
/* 204 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[205],&states[203],&states[200],&states[197]},
/* 205 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[3],NULL,NULL,NULL,NULL,NULL},
          &states[203],&states[204],&states[196],&states[250]},
/* 206 */ {"in the thunderstorm","half-buried in the underbrush",
          FAZ160,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[195],&states[246],&states[251],&states[198]},
/* 207 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[4],NULL,NULL,NULL,NULL,NULL},
          &states[248],&states[245],&states[203],&states[175]},
/* 208 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[209],&states[244],&states[205],&states[204]},
/* 209 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[228],&states[208],&states[210],&states[229]},
/* 210 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[0],NULL,NULL,NULL,NULL,NULL},
          &states[221],&states[225],&states[211],&states[209]},
/* 211 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[214],&states[224],&states[212],&states[210]},
/* 212 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[1],NULL,NULL,NULL,NULL,NULL},
          &states[213],&states[218],&states[240],&states[211]},
/* 213 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[2],NULL,NULL,NULL,NULL,NULL},
          &states[215],&states[212],&states[241],&states[214]},
/* 214 */ {"in the jungle","in the underbrush",
          FAZ159,
          nocmd,
          NULL,
          1,{&objcts[151],NULL,NULL,NULL,NULL,NULL},
          &states[220],&states[211],&states[213],&states[221]},
/* 215 */ {"in the jungle","in the underbrush",
          FAZ158,
          nocmd,
          NULL,
          2,{&objcts[3],&objcts[150],NULL,NULL,NULL,NULL},
          &states[216],&states[213],&states[242],&states[220]},
/* 216 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[217],&states[215],&states[243],&states[219]},
/* 217 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[4],NULL,NULL,NULL,NULL,NULL},
          &states[239],&states[216],&states[239],&states[218]},
/* 218 */ {"in the jungle","in the underbrush",
          FAZ157,
          nocmd,
          NULL,
          1,{&objcts[149],NULL,NULL,NULL,NULL,NULL},
          &states[212],&states[219],&states[217],&states[224]},
/* 219 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[218],&states[220],&states[216],&states[223]},
/* 220 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[0],NULL,NULL,NULL,NULL,NULL},
          &states[219],&states[214],&states[215],&states[222]},
/* 221 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[222],&states[210],&states[214],&states[228]},
/* 222 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[1],NULL,NULL,NULL,NULL,NULL},
          &states[223],&states[221],&states[220],&states[227]},
/* 223 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[2],NULL,NULL,NULL,NULL,NULL},
          &states[224],&states[222],&states[219],&states[226]},
/* 224 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[211],&states[223],&states[218],&states[225]},
/* 225 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[3],NULL,NULL,NULL,NULL,NULL},
          &states[210],&states[226],&states[224],&states[233]},
/* 226 */ {"in the jungle","in the underbrush",
          FAZ156,
          nocmd,
          NULL,
          1,{&objcts[148],NULL,NULL,NULL,NULL,NULL},
          &states[225],&states[227],&states[223],&states[232]},
/* 227 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[4],NULL,NULL,NULL,NULL,NULL},
          &states[226],&states[228],&states[222],&states[231]},
/* 228 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[227],&states[209],&states[221],&states[230]},
/* 229 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[230],&states[234],&states[209],&states[238]},
/* 230 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[0],NULL,NULL,NULL,NULL,NULL},
          &states[231],&states[229],&states[228],&states[237]},
/* 231 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[232],&states[230],&states[227],&states[236]},
/* 232 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[1],NULL,NULL,NULL,NULL,NULL},
          &states[233],&states[231],&states[226],&states[235]},
/* 233 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[2],NULL,NULL,NULL,NULL,NULL},
          &states[209],&states[232],&states[225],&states[234]},
/* 234 */ {"in the jungle","in the underbrush",
          FAZ155,
          nocmd,
          NULL,
          1,{&objcts[147],NULL,NULL,NULL,NULL,NULL},
          &states[229],&states[235],&states[233],&states[243]},
/* 235 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[3],NULL,NULL,NULL,NULL,NULL},
          &states[234],&states[236],&states[232],&states[242]},
/* 236 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[235],&states[237],&states[231],&states[241]},
/* 237 */ {"in the jungle","in the underbrush",
          FAZ154,
          nocmd,
          NULL,
          2,{&objcts[4],&objcts[146],NULL,NULL,NULL,NULL},
          &states[236],&states[238],&states[230],&states[240]},
/* 238 */ {"in the jungle","in the underbrush",
          FAZ1544,
          nocmd,
          NULL,
          1,{&objcts[117],NULL,NULL,NULL,NULL,NULL},
          &states[237],&states[243],&states[229],&states[239]},
/* 239 */ {"in the jungle","in the underbrush",
          FAZ153,
          nocmd,
          NULL,
          1,{&objcts[145],NULL,NULL,NULL,NULL,NULL},
          &states[240],&states[217],&states[238],&states[217]},
/* 240 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[0],NULL,NULL,NULL,NULL,NULL},
          &states[241],&states[239],&states[237],&states[212]},
/* 241 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[242],&states[240],&states[236],&states[213]},
/* 242 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[1],NULL,NULL,NULL,NULL,NULL},
          &states[243],&states[241],&states[235],&states[215]},
/* 243 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[2],NULL,NULL,NULL,NULL,NULL},
          &states[238],&states[242],&states[234],&states[216]},
/* 244 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[208],&states[247],&states[197],&states[252]},
/* 245 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[3],NULL,NULL,NULL,NULL,NULL},
          &states[207],&states[249],&states[201],&states[198]},
/* 246 */ {"in the jungle","in the underbrush",
          FAZ162,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[206],&states[250],&states[195],&states[197]},
/* 247 */ {"in the jungle","in the underbrush",
          FAZ163,
          nocmd,
          NULL,
          1,{&objcts[4],NULL,NULL,NULL,NULL,NULL},
          &states[199],&states[253],&states[196],&states[204]},
/* 248 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[252],&states[207],&states[198],&states[203]},
/* 249 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[245],&states[197],&states[247],&states[204]},
/* 250 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[0],NULL,NULL,NULL,NULL,NULL},
          &states[246],&states[197],&states[205],&states[200]},
/* 251 */ {"standing before the oddlewokkus","in the underbrush",
          FAZ142,
          cm251,
          NULL,
          1,{&objcts[138],NULL,NULL,NULL,NULL,NULL},
          &states[253],&states[197],&states[198],&states[206]},
/* 252 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[1],NULL,NULL,NULL,NULL,NULL},
          &states[194],&states[248],&states[244],&states[199]},
/* 253 */ {"in the thunderstorm","half-buried in the underbrush",
          FAZ160,
          nocmd,
          NULL,
          1,{&objcts[2],NULL,NULL,NULL,NULL,NULL},
          &states[247],&states[251],&states[250],&states[205]},
/* 254 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[257],&states[83],&states[82],&states[256]},
/* 255 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[3],NULL,NULL,NULL,NULL,NULL},
          &states[255],&states[255],&states[261],&states[259]},
/* 256 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[258],&states[84],&states[254],&states[258]},
/* 257 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[4],NULL,NULL,NULL,NULL,NULL},
          &states[258],&states[254],&states[257],&states[258]},
/* 258 */ {"in the jungle","in the underbrush",
          FAZ122,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[261],&states[256],&states[257],&states[261]},
/* 259 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[259],&states[259],&states[255],&states[260]},
/* 260 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[0],NULL,NULL,NULL,NULL,NULL},
          &states[260],&states[260],&states[259],&states[262]},
/* 261 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[261],&states[258],&states[258],&states[255]},
/* 262 */ {"in the jungle","in the underbrush",
          FAZ132,
          nocmd,
          NULL,
          1,{&objcts[122],NULL,NULL,NULL,NULL,NULL},
          &states[276],&states[260],&states[260],&states[276]},
/* 263 */ {"in the thunderstorm","half-buried in the underbrush",
          FAZ160,
          nocmd,
          NULL,
          1,{&objcts[2],NULL,NULL,NULL,NULL,NULL},
          &states[283],&states[277],&states[264],&states[280]},
/* 264 */ {"in the thunderstorm","half-buried in the underbrush",
          FAZ160,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[264],&states[264],&states[265],&states[263]},
/* 265 */ {"in the jungle","in the underbrush",
          FAZ161,
          nocmd,
          NULL,
          1,{&objcts[3],NULL,NULL,NULL,NULL,NULL},
          &states[265],&states[266],&states[266],&states[264]},
/* 266 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[265],&states[267],&states[266],&states[266]},
/* 267 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[4],NULL,NULL,NULL,NULL,NULL},
          &states[266],&states[268],&states[267],&states[267]},
/* 268 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[267],&states[268],&states[268],&states[269]},
/* 269 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[269],&states[269],&states[268],&states[270]},
/* 270 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[0],NULL,NULL,NULL,NULL,NULL},
          &states[270],&states[270],&states[269],&states[271]},
/* 271 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[271],&states[271],&states[270],&states[272]},
/* 272 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[1],NULL,NULL,NULL,NULL,NULL},
          &states[272],&states[272],&states[271],&states[273]},
/* 273 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[2],NULL,NULL,NULL,NULL,NULL},
          &states[273],&states[274],&states[272],&states[273]},
/* 274 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[273],&states[275],&states[274],&states[274]},
/* 275 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          1,{&objcts[3],NULL,NULL,NULL,NULL,NULL},
          &states[274],&states[275],&states[276],&states[275]},
/* 276 */ {"in the jungle","in the underbrush",
          FAZ120,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[276],&states[276],&states[262],&states[275]},
/* 277 */ {"in the thunderstorm","half-buried in the underbrush",
          FAZ160,
          nocmd,
          NULL,
          1,{&objcts[4],NULL,NULL,NULL,NULL,NULL},
          &states[263],&states[277],&states[277],&states[278]},
/* 278 */ {"in the thunderstorm","in the underbrush",
          FAZ160,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[282],&states[278],&states[277],&states[279]},
/* 279 */ {"in the thunderstorm","half-buried in the underbrush",
          FAZ160,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[280],&states[279],&states[278],&states[279]},
/* 280 */ {"in the thunderstorm","half-buried in the underbrush",
          FAZ160,
          nocmd,
          NULL,
          1,{&objcts[0],NULL,NULL,NULL,NULL,NULL},
          &states[281],&states[279],&states[263],&states[280]},
/* 281 */ {"in the thunderstorm","in the underbrush",
          FAZ160,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[281],&states[280],&states[282],&states[281]},
/* 282 */ {"in the thunderstorm","half-buried in the underbrush",
          FAZ160,
          nocmd,
          NULL,
          1,{&objcts[1],NULL,NULL,NULL,NULL,NULL},
          &states[282],&states[284],&states[283],&states[281]},
/* 283 */ {"in the thunderstorm","half-buried in the underbrush",
          FAZ160,
          nocmd,
          NULL,
          1,{&objcts[2],NULL,NULL,NULL,NULL,NULL},
          &states[283],&states[263],&states[283],&states[282]},
/* 284 */ {"standing before the blub","in the underbrush",
          FAZ145,
          cm284,
          NULL,
          1,{&objcts[139],NULL,NULL,NULL,NULL,NULL},
          &states[282],&states[278],&states[263],&states[280]},
/* 285 */ {"in the south reception area","on the desk",
          FAZ285,
          nocmd,
          NULL,
          3,{&objcts[3],&objcts[69],&objcts[80],NULL,NULL,NULL},
          &states[292],&states[0],&states[289],NULL},
/* 286 */ {"on the east-gate walkway","on the walkway",
          FAZ286,
          nocmd,
          NULL,
          2,{&objcts[80],&objcts[116],NULL,NULL,NULL,NULL},
          NULL,&states[291],&states[1],&states[296]},
/* 287 */ {"on the north-gate walkway","on the walkway",
          FAZ287,
          nocmd,
          NULL,
          2,{&objcts[4],&objcts[80],NULL,NULL,NULL,NULL},
          &states[2],&states[299],NULL,&states[300]},
/* 288 */ {"in the west reception area","on the desk",
          FAZ288,
          nocmd,
          NULL,
          2,{&objcts[80],&objcts[69],NULL,NULL,NULL,NULL},
          NULL,&states[295],&states[298],&states[3]},
/* 289 */ {"in the room with scintillating walls","on the floor",
          FAZ289,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[290],NULL,NULL,&states[285]},
/* 290 */ {"in the short corridor","on the floor",
          FAZ290,
          cm290,
          NULL,
          2,{&objcts[0],&objcts[71],NULL,NULL,NULL,NULL},
          &states[291],&states[289],NULL,NULL},
/* 291 */ {"in the Hall of Umflungoo","on the floor",
          FAZ291,
          umflun,
          NULL,
          2,{&objcts[123],&objcts[124],NULL,NULL,NULL,NULL},
          &states[286],&states[290],NULL,NULL},
/* 292 */ {"in the dogleg hallway","on the floor",
          FAZ292,
          nocmd,
          NULL,
          2,{&objcts[1],&objcts[70],NULL,NULL,NULL,NULL},
          &states[294],&states[285],NULL,&states[293]},
/* 293 */ {"in the vibrating cubicle","in the dirt",
          FAZ293,
          nocmd,
          NULL,
          2,{&objcts[2],&objcts[70],NULL,NULL,NULL,NULL},
          &states[295],NULL,&states[292],NULL},
/* 294 */ {"in the hall with the faded map","on the floor",
          FAZ294,
          nocmd,
          NULL,
          1,{&objcts[73],NULL,NULL,NULL,NULL,NULL},
          &states[298],&states[292],&states[296],&states[295]},
/* 295 */ {"in the room with the weird substances","on the floor",
          FAZ295,
          nocmd,
          NULL,
          3,{&objcts[3],&objcts[75],&objcts[76],NULL,NULL,NULL},
          &states[288],&states[293],&states[294],NULL},
/* 296 */ {"by the glowing sphere","on the walkway",
          FAZ296,
          nocmd,
          NULL,
          3,{&objcts[77],&objcts[78],&objcts[79],NULL,NULL,NULL},
          &states[297],NULL,&states[286],&states[294]},
/* 297 */ {"in the courtyard","on the ground",
          FAZ297,
          nocmd,
          NULL,
          2,{&objcts[4],&objcts[79],NULL,NULL,NULL,NULL},
          NULL,&states[296],NULL,&states[298]},
/* 298 */ {"in the Foon-Ball Emporium","on the floor",
          FAZ298,
          foon,
          NULL,
          1,{&objcts[81],NULL,NULL,NULL,NULL,NULL},
          &states[300],&states[294],&states[297],&states[288]},
/* 299 */ {"in the ozone chamber","on the floor",
          FAZ299,
          osmo,
          NULL,
          1,{&objcts[74],NULL,NULL,NULL,NULL,NULL},
          &states[287],NULL,NULL,NULL},
/* 300 */ {"on the glowing pathway","on the path",
          FAZ300,
          nocmd,
          NULL,
          1,{&objcts[0],NULL,NULL,NULL,NULL,NULL},
          &states[301],&states[298],&states[287],&states[302]},
/* 301 */ {"in the jet black chamber","on the floor",
          FAZ301,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          NULL,&states[300],NULL,&states[303]},
/* 302 */ {"inside the dome with many lights","on the floor",
          FAZ302,
          cm302,
          NULL,
          2,{&objcts[1],&objcts[82],NULL,NULL,NULL,NULL},
          &states[303],NULL,&states[300],NULL},
/* 303 */ {"in the hall of voices","on the floor",
          FAZ303,
          cm303,
          NULL,
          1,{&objcts[2],NULL,NULL,NULL,NULL,NULL},
          NULL,&states[302],&states[301],NULL},
/* 304 */ {"in the short corridor","on the floor",
          FAZ304,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          NULL,NULL,&states[305],&states[299]},
/* 305 */ {"in the clean-swept chamber","on the floor",
          FAZ305,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          NULL,&states[306],&states[307],&states[304]},
/* 306 */ {"in the room with the wheel","on the floor",
          FAZ306,
          cm306,
          NULL,
          2,{&objcts[88],&objcts[115],NULL,NULL,NULL,NULL},
          &states[305],NULL,&states[308],NULL},
/* 307 */ {"in the room with the grinfrazzitz","on the floor",
          FAZ307,
          cm307,
          NULL,
          2,{&objcts[4],&objcts[89],NULL,NULL,NULL,NULL},
          NULL,&states[308],NULL,&states[305]},
/* 308 */ {"in the room full of tables","on one of the tables",
          FAZ308,
          nocmd,
          NULL,
          1,{&objcts[90],NULL,NULL,NULL,NULL,NULL},
          &states[307],NULL,&states[309],&states[306]},
/* 309 */ {"in the long corridor","on the floor",
          FAZ309,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          NULL,&states[311],NULL,&states[308]},
/* 310 */ {"in the western spark chamber","on the floor",
          FAZ310,
          cm310,
          NULL,
          2,{&objcts[0],&objcts[91],NULL,NULL,NULL,NULL},
          NULL,NULL,&states[311],NULL},
/* 311 */ {"in the middle spark chamber","on the floor",
          FAZ311,
          cm311,
          NULL,
          1,{&objcts[91],NULL,NULL,NULL,NULL,NULL},
          &states[309],NULL,&states[312],&states[310]},
/* 312 */ {"in the eastern spark chamber","on the floor",
          FAZ312,
          cm312,
          NULL,
          2,{&objcts[1],&objcts[91],NULL,NULL,NULL,NULL},
          NULL,NULL,NULL,&states[311]},
/* 313 */ {"in the glowing gold chamber","on the floor",
          FAZ313,
          nocmd,
          NULL,
          1,{&objcts[2],NULL,NULL,NULL,NULL,NULL},
          NULL,NULL,&states[314],NULL},
/* 314 */ {"in the soft carpeted area","on the carpet",
          FAZ314,
          nocmd,
          NULL,
          1,{&objcts[92],NULL,NULL,NULL,NULL,NULL},
          NULL,&states[316],&states[315],&states[313]},
/* 315 */ {"in the observation chamber","on the floor",
          FAZ315,
          nocmd,
          NULL,
          2,{&objcts[3],&objcts[93],NULL,NULL,NULL,NULL},
          NULL,NULL,NULL,&states[314]},
/* 316 */ {"at the restricted area entrance","on the floor",
          FAZ316,
          nocmd,
          NULL,
          1,{&objcts[94],NULL,NULL,NULL,NULL,NULL},
          &states[314],&states[318],&states[317],NULL},
/* 317 */ {"in the midst of the intricate machinery","among the machines",
          FAZ317,
          nocmd,
          NULL,
          1,{&objcts[95],NULL,NULL,NULL,NULL,NULL},
          NULL,&states[319],NULL,&states[316]},
/* 318 */ {"in the metastatic control chamber","beside the control panel",
          FAZ768,
          cm318,
          NULL,
          1,{&objcts[96],NULL,NULL,NULL,NULL,NULL},
          &states[316],NULL,&states[319],NULL},
/* 319 */ {"in the metastatic transfer chamber","on the floor",
          FAZ319,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[317],NULL,NULL,&states[318]},
/* 320 */ {"in the room with the hopper","in front of the hopper",
          FAZ320,
          cm320,
          NULL,
          2,{&objcts[0],&objcts[97],NULL,NULL,NULL,NULL},
          NULL,&states[323],&states[321],NULL},
/* 321 */ {"in the console room","beside the console",
          FAZ321,
          cm321,
          NULL,
          1,{&objcts[98],NULL,NULL,NULL,NULL,NULL},
          NULL,&states[322],NULL,&states[320]},
/* 322 */ {"in the room with 5 buttons","on the floor",
          FAZ322,
          cm322,
          NULL,
          2,{&objcts[1],&objcts[99],NULL,NULL,NULL,NULL},
          &states[321],NULL,NULL,&states[323]},
/* 323 */ {"in the long chamber with globes in the ceiling","on the floor",
          FAZ323,
          nocmd,
          NULL,
          2,{&objcts[2],&objcts[100],NULL,NULL,NULL,NULL},
          &states[320],NULL,&states[322],&states[324]},
/* 324 */ {"in the laboratory reception area","on the desk",
          FAZ324,
          nocmd,
          NULL,
          1,{&objcts[101],NULL,NULL,NULL,NULL,NULL},
          &states[325],NULL,&states[323],NULL},
/* 325 */ {"in the long north-south corridor","on the floor",
          FAZ325,
          nocmd,
          NULL,
          1,{&objcts[3],NULL,NULL,NULL,NULL,NULL},
          &states[326],&states[324],NULL,NULL},
/* 326 */ {"in the long north-south corridor","on the floor",
          FAZ326,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[327],&states[325],NULL,NULL},
/* 327 */ {"in the long north-south corridor","on the floor",
          FAZ327,
          nocmd,
          NULL,
          1,{&objcts[4],NULL,NULL,NULL,NULL,NULL},
          &states[328],&states[326],NULL,NULL},
/* 328 */ {"in the long north-south corridor","on the floor",
          FAZ328,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[329],&states[327],NULL,NULL},
/* 329 */ {"in the room with the strange light sculpture","on the floor",
          FAZ329,
          nocmd,
          NULL,
          2,{&objcts[102],&objcts[103],NULL,NULL,NULL,NULL},
          &states[331],&states[328],&states[330],NULL},
/* 330 */ {"in the transporter lobby","on the floor",
          FAZ330,
          cm330,
          NULL,
          2,{&objcts[0],&objcts[71],NULL,NULL,NULL,NULL},
          &states[332],NULL,NULL,&states[329]},
/* 331 */ {"in the room with the granfalloon","on the floor",
          FAZ331,
          cm331,
          NULL,
          1,{&objcts[104],NULL,NULL,NULL,NULL,NULL},
          NULL,&states[329],&states[332],NULL},
/* 332 */ {"in the nuevo/cathedral","in the aisle",
          FAZ332,
          nocmd,
          NULL,
          2,{&objcts[1],&objcts[105],NULL,NULL,NULL,NULL},
          NULL,&states[330],&states[333],&states[331]},
/* 333 */ {"standing by the giant ribbenfratz","on the floor",
          FAZ333,
          cm333,
          NULL,
          2,{&objcts[2],&objcts[106],NULL,NULL,NULL,NULL},
          NULL,NULL,NULL,&states[332]},
/* 334 */ {"in limbo","in limbo with you",
          FAZ334,
          cm334,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[334],&states[334],&states[334],&states[334]},
/* 335 */ {"in the low slung passageway","in the dirt",
          FAZ335,
          nocmd,
          NULL,
          2,{&objcts[3],&objcts[70],NULL,NULL,NULL,NULL},
          NULL,NULL,&states[336],NULL},
/* 336 */ {"in the hall with the stone floor","on the floor",
          FAZ336,
          cm336,
          NULL,
          2,{&objcts[70],&objcts[83],NULL,NULL,NULL,NULL},
          &states[339],NULL,&states[337],&states[335]},
/* 337 */ {"in among the floating globules","on the floor",
          FAZ337,
          cm337,
          NULL,
          2,{&objcts[4],&objcts[107],NULL,NULL,NULL,NULL},
          &states[338],NULL,NULL,&states[336]},
/* 338 */ {"in the room bathed in indefinable light","on the floor",
          FAZ338,
          cm338,
          NULL,
          1,{&objcts[108],NULL,NULL,NULL,NULL,NULL},
          NULL,&states[337],NULL,&states[339]},
/* 339 */ {"in the short passageway","on the floor",
          FAZ339,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[343],&states[336],&states[338],NULL},
/* 340 */ {"in the north/south passageway","in the dirt",
          FAZ340,
          nocmd,
          NULL,
          2,{&objcts[0],&objcts[70],NULL,NULL,NULL,NULL},
          &states[341],NULL,NULL,NULL},
/* 341 */ {"on the observation deck","on the deck",
          FAZ341,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[346],&states[340],&states[342],NULL},
/* 342 */ {"standing beside the giant coils","on the floor",
          FAZ342,
          nocmd,
          NULL,
          2,{&objcts[1],&objcts[109],NULL,NULL,NULL,NULL},
          &states[345],NULL,&states[343],&states[341]},
/* 343 */ {"in the room with the large hopper","beside the hopper",
          FAZ343,
          cm343,
          NULL,
          2,{&objcts[2],&objcts[110],NULL,NULL,NULL,NULL},
          &states[344],&states[339],NULL,&states[342]},
/* 344 */ {"in the room with many desks","on one of the desks",
          FAZ344,
          nocmd,
          NULL,
          1,{&objcts[111],NULL,NULL,NULL,NULL,NULL},
          &states[348],&states[343],NULL,&states[345]},
/* 345 */ {"in front of the console","on the floor",
          FAZ345,
          cm345,
          NULL,
          2,{&objcts[3],&objcts[112],NULL,NULL,NULL,NULL},
          &states[347],&states[342],&states[344],NULL},
/* 346 */ {"in the hallway","on the floor",
          FAZ402,
          nocmd,
          NULL,
          1,{&objcts[71],NULL,NULL,NULL,NULL,NULL},
          &states[351],&states[341],&states[347],NULL},
/* 347 */ {"at the hallway junction","on the floor",
          FAZ347,
          nocmd,
          NULL,
          2,{&objcts[4],&objcts[113],NULL,NULL,NULL,NULL},
          &states[350],&states[345],&states[348],&states[346]},
/* 348 */ {"in the hallway","on the floor",
          FAZ348,
          nocmd,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          &states[349],&states[344],NULL,&states[347]},
/* 349 */ {"in the room with the box on the wall","on the floor",
          FAZ349,
          cm349,
          NULL,
          1,{&objcts[114],NULL,NULL,NULL,NULL,NULL},
          NULL,&states[348],NULL,&states[350]},
/* 350 */ {"in the room full of white mist","at your feet",
          FAZ350,
          nocmd,
          NULL,
          1,{&objcts[0],NULL,NULL,NULL,NULL,NULL},
          NULL,&states[347],&states[349],NULL},
/* 351 */ {"in the weird egg shaped chamber","on the floor",
          FAZ351,
          cm351,
          NULL,
          1,{&objcts[72],NULL,NULL,NULL,NULL,NULL},
          NULL,&states[346],NULL,NULL},
/* 352 */ {"nowhere","this is a bug",
          FAZ352,
          cm352,
          NULL,
          0,{NULL,NULL,NULL,NULL,NULL,NULL},
          NULL,NULL,NULL,NULL}
};
